function tableout = importfile1(workbookFile,sheetName,startRow,endRow)
%IMPORTFILE1 Import data from a spreadsheet
%   DATA = IMPORTFILE1(FILE) reads data from the first worksheet in the
%   Microsoft Excel spreadsheet file named FILE and returns the data as a
%   table.
%
%   DATA = IMPORTFILE1(FILE,SHEET) reads from the specified worksheet.
%
%   DATA = IMPORTFILE1(FILE,SHEET,STARTROW,ENDROW) reads from the specified
%   worksheet for the specified row interval(s). Specify STARTROW and
%   ENDROW as a pair of scalars or vectors of matching size for
%   dis-contiguous row intervals. To read to the end of the file specify an
%   ENDROW of inf.%
% Example:
%   SunEarthToolsAnnualSunPath20181519894286943 = importfile1('SunEarthTools_AnnualSunPath_2018_1519894286943.xlsx','SunEarthTools_AnnualSunPath_201',1,367);
%
%   See also XLSREAD.

% Auto-generated by MATLAB on 2018/03/01 15:19:23

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 3
    startRow = 1;
    endRow = 367;
end

%% Import the data
[~, ~, raw] = xlsread(workbookFile, sheetName, sprintf('A%d:AW%d',startRow(1),endRow(1)));
for block=2:length(startRow)
    [~, ~, tmpRawBlock] = xlsread(workbookFile, sheetName, sprintf('A%d:AW%d',startRow(block),endRow(block)));
    raw = [raw;tmpRawBlock]; %#ok<AGROW>
end
stringVectors = string(raw(:,[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49]));
stringVectors(ismissing(stringVectors)) = '';

%% Create table
tableout = table;

%% Allocate imported array to column variable names
tableout.coo63095089_216164564 = stringVectors(:,1);
tableout.E000000 = stringVectors(:,2);
tableout.A000000 = stringVectors(:,3);
tableout.E010000 = stringVectors(:,4);
tableout.rrrrrrrr = stringVectors(:,5);
tableout.E020000 = stringVectors(:,6);
tableout.A020000 = stringVectors(:,7);
tableout.E030000 = stringVectors(:,8);
tableout.A030000 = stringVectors(:,9);
tableout.E040000 = stringVectors(:,10);
tableout.A040000 = stringVectors(:,11);
tableout.E050000 = stringVectors(:,12);
tableout.A050000 = stringVectors(:,13);
tableout.E060000 = stringVectors(:,14);
tableout.A060000 = stringVectors(:,15);
tableout.E070000 = stringVectors(:,16);
tableout.A070000 = stringVectors(:,17);
tableout.E080000 = stringVectors(:,18);
tableout.A080000 = stringVectors(:,19);
tableout.E090000 = stringVectors(:,20);
tableout.A090000 = stringVectors(:,21);
tableout.E100000 = stringVectors(:,22);
tableout.A100000 = stringVectors(:,23);
tableout.E110000 = stringVectors(:,24);
tableout.A110000 = stringVectors(:,25);
tableout.E120000 = stringVectors(:,26);
tableout.A120000 = stringVectors(:,27);
tableout.E130000 = stringVectors(:,28);
tableout.A130000 = stringVectors(:,29);
tableout.E140000 = stringVectors(:,30);
tableout.A140000 = stringVectors(:,31);
tableout.E150000 = stringVectors(:,32);
tableout.A150000 = stringVectors(:,33);
tableout.E160000 = stringVectors(:,34);
tableout.A160000 = stringVectors(:,35);
tableout.E170000 = stringVectors(:,36);
tableout.A170000 = stringVectors(:,37);
tableout.E180000 = stringVectors(:,38);
tableout.A180000 = stringVectors(:,39);
tableout.E190000 = stringVectors(:,40);
tableout.A190000 = stringVectors(:,41);
tableout.E200000 = stringVectors(:,42);
tableout.A200000 = stringVectors(:,43);
tableout.E210000 = stringVectors(:,44);
tableout.A210000 = stringVectors(:,45);
tableout.E220000 = stringVectors(:,46);
tableout.A220000 = stringVectors(:,47);
tableout.E230000 = stringVectors(:,48);
tableout.A230000 = stringVectors(:,49);

